# ------------------------------------------------------------
# analysis_options.yaml
# Fichier de configuration pour l'analyse statique Dart/Flutter
# ------------------------------------------------------------

# 1. Inclut une base de règles Flutter officielle
#    → apporte déjà un set de bonnes pratiques de Google.
include: package:flutter_lints/flutter.yaml

analyzer:
  # 2. Déclare les plugins à charger par l'analyseur.
  #    - "custom_lint" est le moteur.
  #    - "riverpod_lint" s'appuie dessus pour ajouter ses propres règles.
  plugins:
    - custom_lint

  # 3. Exclut certains fichiers/dossiers de l'analyse.
  #    - "build/**" : fichiers générés par Flutter.
  #    - "*.g.dart", "*.freezed.dart" : code généré automatiquement.
  exclude:
    - build/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

  # 4. Ajuste la sévérité de certaines erreurs.
  #    Exemple : transformer des warnings en erreurs bloquantes.
  errors:
    invalid_assignment: error
    unused_import: warning
    dead_code: info

linter:
  # 5. Active/désactive des règles spécifiques.
  #    → hérite de flutter_lints, tu peux surcharger ici.
  rules:
    avoid_print: true            # Préfère logger plutôt que print()
    prefer_const_constructors: true # Encourage l’usage de const
    always_use_package_imports: true # Importer avec package: plutôt que relatif
    unnecessary_this: true       # Évite "this." inutile
    prefer_final_fields: true    # Rend les champs immuables si possible
    use_super_parameters: true   # Encourage la syntaxe Dart moderne