name: fitness_tracker_app_state_management
description: "Entrainement spartiate"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1
environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter: # SDK Flutter, base de l’application
    sdk: flutter
  cupertino_icons: ^1.0.8 # Icônes iOS (Cupertino)
  introduction_screen: ^4.0.0 # Écrans d’onboarding multi-pages
  uuid: ^4.5.1 # Génération d’identifiants uniques
  flutter_riverpod: ^3.0.1 # State management réactif (Riverpod)
  hooks_riverpod: ^3.0.1 # Utilisation des hooks avec Riverpod
  shared_preferences: ^2.5.3 # Stockage clé/valeur local persistant
  freezed_annotation: ^3.1.0 # Annotations pour classes immuables (Freezed)
  json_annotation: ^4.9.0 # Annotations pour sérialisation JSON
  flutter_hooks: ^0.21.3+1 # Simplifie le cycle de vie avec hooks
  riverpod_annotation: ^3.0.1 # Annotations pour générateurs Riverpod

dev_dependencies:
  flutter_test: # Tests unitaires et widgets pour Flutter
    sdk: flutter
  flutter_lints: ^5.0.0 # Règles de lint recommandées
  build_runner: 2.7.1 # Outil générique pour lancer les générateurs
  riverpod_generator: ^3.0.0 # Générateur de code pour providers Riverpod
  custom_lint: ^0.8.0 # Créer/appliquer des règles de lint personnalisées
  json_serializable: ^6.11.1 # Générateur JSON <-> objets Dart
  riverpod_lint: ^3.0.1
  freezed: ^3.2.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
